
// this file is autogenerated - any modification will be overwritten
// unused symbols will not be linked in the final binary
// generated on 2021-07-16 02:12:54
// by ['../../../../tools/cert.py', '-s', 'api.github.com', '-n', 'github']

#pragma once

////////////////////////////////////////////////////////////
// certificate chain for api.github.com:443

const char* github_host = "api.github.com";
const uint16_t github_port = 443;

// CN: *.github.com => name: __github_com
// not valid before: 2021-03-25 00:00:00
// not valid after:  2022-03-30 23:59:59
const char fingerprint___github_com [] PROGMEM = "96:84:07:df:0b:1c:f6:58:14:df:d7:33:35:57:51:9b:15:4d:8c:e7";
const char pubkey___github_com [] PROGMEM = R"PUBKEY(
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElL9/+0TidTIALPfU/tiS6pI8zAIk
rU4pohUldVc0bb6O3FARl3cnqIDK9SoF65z3xiR6XsnFS8F0Oy/chXR/kQ==
-----END PUBLIC KEY-----
)PUBKEY";

// http://cacerts.digicert.com/DigiCertHighAssuranceTLSHybridECCSHA2562020CA1.crt
// CN: DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1 => name: DigiCert_High_Assurance_TLS_Hybrid_ECC_SHA256_2020_CA1
// not valid before: 2020-12-17 00:00:00
// not valid after:  2030-12-16 23:59:59
const char cert_mby_fr [] PROGMEM = R"CERT(
-----BEGIN CERTIFICATE-----
MIIGGjCCBQKgAwIBAgISBGBgo/3D/pIGIbdbqOBficIAMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTA1MzAxODQ1NDVaFw0yMTA4MjgxODQ1NDVaMBUxEzARBgNVBAMT
CmlvdC5tYnkuZnIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDxrItG
xr3+o61ht61Q1VIuhxdjZLtep0X07iWxEoWCS+GuigELm6KRtsu4XyJaUHf46kqz
OapEWLoZVAS8aFK/nVJWpsDsg6eQdDn/+/9zKdu2+RVCn8SxWz4Wpm+gqw/ne81g
4txKjJvUIjhHRnITPmlYazWldTZcIfaK+5HO0BHlsvrh+4gdYFyNHDRg7nPSoVt3
OohQRlgVQkE520Be1wzlRyQJMA75hKNJ7enigQjPxi+ryvjOcNfgEk9FKAX/4rig
UkTqn+Yox6IDdC5Dy10VUt9EF3ZFI3t/DalMKta4DJpADMCuaihP9L3mRceEIii9
2VNLPqCsemLKFMDnE09SrjP/gy95mhxqMM8kXIYOCwychCHFaTlEqtbcmpa/JlZK
DRGVznDu/c45w6Qrd9elHFeZf1fB/OiawX3/7fYgbNU8Y3aGvSPVadelKYWOe4mm
PZW+o1EW01AnzQ1L57ecTsWj0g0IMWcqTx0tyFjBVkBPGE6apMsJCIlz5uudr28s
oslqLQZUpoawTnM8OkLTIMVx62Jq2kgtc9e28/OCZ0Bl2VTC1fQW2pWJT/3NKA5R
3qFbfe9o/kE9BY+PRXYoOEEmLc/5K7gVk0mB8AI3um3N6yjHlIyfDZOtmik33rPA
QMGnbYEZOeVexHJE8n+lmmHpwUWAlbs/iHxoGQIDAQABo4ICRTCCAkEwDgYDVR0P
AQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMB
Af8EAjAAMB0GA1UdDgQWBBSLtdYzFtXed/2X7ER2HHfPTV2ZSjAfBgNVHSMEGDAW
gBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUH
MAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3Iz
LmkubGVuY3Iub3JnLzAVBgNVHREEDjAMggppb3QubWJ5LmZyMEwGA1UdIARFMEMw
CAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9j
cHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHUAlCC8
Ho7VjWyIcx+CiyIsDdHaTV5sT5Q9YdtOL1hNosIAAAF5vs+SWgAABAMARjBEAiBH
OhYwDV7IjOTWTpIjHZ9QOYvvJRki+lgQsRrSOBoSKAIgObvNGy0xhLSmQHx/mHmc
Xxngxh28cuUaOYbCNeAl3OQAdwB9PvL4j/+IVWgkwsDKnlKJeSvFDngJfy5ql2iZ
fiLw1wAAAXm+z5J7AAAEAwBIMEYCIQC6zk+/mGKzk4pABT4ncnFAPLuSP/44uILU
i0AqK+GpfgIhALyBjL9LZ5Jt0D44qznMeqv9mEtuRuxBYwEWdChtQ9ZHMA0GCSqG
SIb3DQEBCwUAA4IBAQA/YR452Od6Zvf7oz8ZXcoEUeXO1R4D0IqebZM82tKtn6SW
VJ9RwmdUwuOXf9FjklAtdIjNchlRZuc6hMgHSqWhPRGydavgyfEFSjAe1sr025iJ
NtyKMwnqe4IepB30YLIuUpOBKIpgqwCzrmPhUlgNEm4xdyY+Pc5mAuYVTTro05a/
pxZ5KszMPx62kggQg21aRqmZq/2INWu/xUPS3253P8m0Ch4BNAmpAq5atay2fJ6f
ROrWT5xFlybdI4jpSpCxeCo89SUqPogiBaoAnVbcG5/TzpAz5MuZDL3ihgctzNb+
i0xNdC1T+vwvb7HNtHKA788ZntsHos4Ng1I/b8Vh
-----END CERTIFICATE-----
)CERT";

// http://cacerts.digicert.com/DigiCertHighAssuranceEVRootCA.crt
// CN: DigiCert High Assurance EV Root CA => name: DigiCert_High_Assurance_EV_Root_CA
// not valid before: 2006-11-10 00:00:00
// not valid after:  2031-11-10 00:00:00
const char cert_LetsEncrypt_root_CA [] PROGMEM = R"CERT(
-----BEGIN CERTIFICATE-----
MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
-----END CERTIFICATE-----
)CERT";


// end of certificate chain for api.github.com:443
////////////////////////////////////////////////////////////

